### ISSUE TITLE
Libra 2

### ISSUE THREAD

**Issue by skylar2k** [geek1011/koboutils#5]
Hey, would it be possible to add support for the Kobo Libra 2? I believe its Mark 9 and the code name is "Io", that's at least what I figured from libnickel.so but I don't really know how to read asm or use Ghidra so.

**Comment by marcus-crane** [comment]
I just got a Libra 2 today and the version string is `NXXXXXXXXXX,4.1.15,4.30.18838,4.1.15,4.1.15,00000000-0000-0000-0000-000000000388`

For reference, it can be found under `<mount point>/KOBOeReader/.kobo/version`

**Comment by jucor** [comment]
I just got a Libra 2 today too, version string here is:
```
N4181A5005573,4.1.15,4.31.19086,4.1.15,4.1.15,00000000-0000-0000-0000-000000000388
```
It would be great if you could add support for it, please, @pgaskin ! I'd love to use Kobo-UNCaGED, which uses it :) Thank you for your work!
